<?php

$top_nav=array(
    'en'=>array('Home','About','Services','Explore','Medical','Contact'),
    'ar'=>array('بيت','عن','خدمات','يستكشف','طبي','اتصال'),
);


$banner_txt=array(
    'en'=>array('Make Your Dream Live','Adventures fill your soul','Adventure awaits for you','Lets travel to see the world','One Way To Get Out Of Life','Lets find some beautiful place','One Way To Get Out Of Life','Lets find some beautiful place','Embark on a journey to wellness.'),
    'ar'=>array('اجعل حلمك حيًا','المغامرات تملأ روحك','المغامرة في انتظارك','دعونا نسافر لرؤية العالم','طريقة واحدة للخروج من الحياة','دعونا نجد بعض المكان الجميل','طريقة واحدة للخروج من الحياة','دعونا نجد بعض المكان الجميل','الشروع في رحلة إلى العافية.'),
);

$about_us = array(
    'en' => array('ABOUT US','Who We Are','We Leap Visa Travel Agency, where travel dreams become reality. With over 10 years of unparalleled expertise in the travel and visa industry, we have been the guiding compass for countless travelers seeking seamless journeys and unforgettable experiences.'),
    'ar' => array('معلومات عنا','من نحن','وكالة ليب فيزا للسفريات، حيث تصبح أحلام السفر حقيقة. مع أكثر من 10 سنوات من الخبرة التي لا مثيل لها في مجال السفر والتأشيرات، فقد كنا البوصلة التوجيهية لعدد لا يحصى من المسافرين الذين يبحثون عن رحلات سلسة وتجارب لا تنسى.')
);

$our_trip = array(
    'en' => array('OUR TRIP','Since 2013, we have been at the forefront of the travel and visa sector, offering a comprehensive range of services tailored to meet the diverse needs of our clients. From leisure travel to business trips, our experienced team is committed to delivering seamless experiences that exceed expectations. As specialists in visa services, we streamline the often complex process of obtaining visas for travel to more than 13 countries worldwide. With in-depth knowledge of visa requirements and regulations, we guide our clients through every step of the application process, ensuring efficiency and peace of mind. In addition to our visa services, we also offer a wide array of travel solutions, including personalized trip planning, itinerary customization, and accommodation arrangements. Whether you are embarking on a solo adventure or planning a group excursion, our team is here to turn your travel dreams into reality.
    Join us on a journey of discovery and adventure. Experience the world with Leap Visa.'),
    'ar' => array('رحلتنا','منذ عام 2013، كنا في طليعة قطاع السفر والتأشيرات، حيث نقدم مجموعة شاملة من الخدمات المصممة لتلبية الاحتياجات المتنوعة لعملائنا. من السفر الترفيهي إلى رحلات العمل، يلتزم فريقنا ذو الخبرة بتقديم تجارب سلسة تتجاوز التوقعات. باعتبارنا متخصصين في خدمات التأشيرات، فإننا نقوم بتبسيط العملية المعقدة غالبًا للحصول على تأشيرات للسفر إلى أكثر من 13 دولة حول العالم. بفضل المعرفة المتعمقة بمتطلبات ولوائح التأشيرة، نقوم بتوجيه عملائنا خلال كل خطوة من عملية تقديم الطلب، مما يضمن الكفاءة وراحة البال. بالإضافة إلى خدمات التأشيرات التي نقدمها، نقدم أيضًا مجموعة واسعة من حلول السفر، بما في ذلك التخطيط الشخصي للرحلات، وتخصيص خط سير الرحلة، وترتيبات الإقامة. سواء كنت تشرع في مغامرة منفردة أو تخطط لرحلة جماعية، فإن فريقنا موجود لتحويل أحلام السفر الخاصة بك إلى حقيقة.
    انضم إلينا في رحلة الاكتشاف والمغامرة. اكتشف العالم مع Leap Visa.')
);

$why_choose_us = array(
    'en' => array('WHY CHOOSE US?','We Make Your Dream Come True','At We Leap Visa Travel Agency, we are more than just travel facilitators - we arere dream enablers. With meticulous attention to detail and a passion for crafting unforgettable experiences, we take your travel aspirations and turn them into reality. Whether its exploring ancient ruins in Greece, savoring street food in Thailand, or studying abroad in Europe, we arere here to make your dream journeys come true. Let us be your partners in adventure, guiding you every step of the way towards your next unforgettable experience.','Lets Travel And Call It A Plan','At We Leap Visa Travel Agency, we believe that every journey begins with a single step and every adventure starts with a dream. Let&#39;s turn your wanderlust into a well-crafted plan. Whether you&#39;re envisioning a relaxing beach getaway, an exhilarating safari, or a cultural immersion in a bustling metropolis, we&#39;re here to transform your travel aspirations into a meticulously planned itinerary. Together, let&#39;s embark on a journey where every moment is an opportunity for discovery and every destination becomes a cherished memory. Let&#39;s travel and call it a plan.','Where You Go There You Are','At We Leap Visa Travel Agency, we understand that the true essence of travel lies not only in the destinations you visit but also in the experiences you accumulate along the way. Whether you&#39;re wandering through cobblestone streets in Europe, marveling at natural wonders in South America, or immersing yourself in the vibrant cultures of Asia, each journey is a reflection of your unique spirit and curiosity. Wherever your wanderlust takes you, we&#39;re here to ensure that every moment is filled with wonder, discovery, and unforgettable memories. Because in the end, it&#39;s not just about where you go, but the person you become along the way.','Adventures Are The Best Way To Learn','At We Leap Visa Travel Agency, we believe that adventures are not just about exploring new places but also about discovering oneself. Whether you&#39;re trekking through rugged mountains, diving into crystal-clear waters, or immersing yourself in local cultures, every adventure is an opportunity for growth and learning. From the challenges you overcome to the connections you make with people from around the world, each experience adds depth to your understanding of the world and yourself. Let us be your guides on this journey of discovery, where every adventure is a lesson waiting to be learned.'),
    'ar' => array('لماذا أخترتنا؟','نحن نجعل حلمك حقيقة','نحن وكالة Leap Visa للسفريات، نحن أكثر من مجرد ميسري سفر - نحن عوامل تمكين الأحلام. مع الاهتمام الدقيق بالتفاصيل والشغف لصياغة تجارب لا تُنسى، فإننا نأخذ تطلعات السفر الخاصة بك ونحولها إلى حقيقة. سواء كان الأمر يتعلق باستكشاف الآثار القديمة في اليونان، أو تذوق أطعمة الشوارع في تايلاند، أو الدراسة بالخارج في أوروبا، فنحن هنا لتحقيق رحلات أحلامك. اسمح لنا أن نكون شركاءك في المغامرة، ونرشدك في كل خطوة على الطريق نحو تجربتك التالية التي لا تُنسى.','دعونا نسافر ونسميها خطة','في وكالة وي ليب فيزا للسفريات، نؤمن بأن كل رحلة تبدأ بخطوة واحدة وكل مغامرة تبدأ بحلم. دعنا نحول حبك للتجوال إلى خطة جيدة الإعداد. سواء كنت تتخيل إجازة مريحة على الشاطئ، أو رحلة سفاري مبهجة، أو انغماسًا ثقافيًا في مدينة صاخبة، فنحن هنا لتحويل تطلعاتك في السفر إلى خط سير رحلة مخطط له بدقة. معًا، دعونا نبدأ رحلة حيث كل لحظة هي فرصة للاكتشاف وكل وجهة تصبح ذكرى عزيزة. دعونا نسافر ونسميها خطة.','أين تذهب هناك أنت','في وكالة We Leap Visa للسفريات، ندرك أن الجوهر الحقيقي للسفر لا يكمن فقط في الوجهات التي تزورها ولكن أيضًا في التجارب التي تتراكم على طول الطريق. سواء كنت تتجول في الشوارع المرصوفة بالحصى في أوروبا، أو تتعجب من العجائب الطبيعية في أمريكا الجنوبية، أو تغمر نفسك في الثقافات النابضة بالحياة في آسيا، فإن كل رحلة هي انعكاس لروحك الفريدة وفضولك. أينما يأخذك حب التجوال، نحن هنا للتأكد من أن كل لحظة مليئة بالعجائب والاكتشافات والذكريات التي لا تنسى. لأنه في النهاية، لا يتعلق الأمر بالمكان الذي تذهب إليه فحسب، بل بالشخص الذي ستصبح عليه على طول الطريق.','المغامرات هي أفضل طريقة للتعلم','في وكالة We Leap Visa للسفريات، نؤمن بأن المغامرات لا تقتصر على استكشاف أماكن جديدة فحسب، بل تتعلق أيضًا باكتشاف الذات. سواء كنت تتجول عبر الجبال الوعرة، أو تغوص في المياه الصافية، أو تنغمس في الثقافات المحلية، فإن كل مغامرة تمثل فرصة للنمو والتعلم. بدءًا من التحديات التي تغلبت عليها وحتى الاتصالات التي تقيمها مع أشخاص من جميع أنحاء العالم، تضيف كل تجربة عمقًا إلى فهمك للعالم ونفسك. دعنا نكون مرشدين لك في هذه الرحلة الاستكشافية، حيث تكون كل مغامرة بمثابة درس ينتظر تعلمه.')
);

$video_txt = array(
    'en' => array('Your Gateway To Seamless Adventures Worldwide! Unlocking Borders, Embracing Cultures, And Making Every Destination Yours.'),
    'ar' => array('بوابتك إلى مغامرات سلسة حول العالم! فتح الحدود، واحتضان الثقافات، وجعل كل وجهة لك.')
);

$our_services = array ( 
    'en' => array('OUR SERVICES','Visa Processing','We specialize in simplifying visa processing for travelers to over 15 countries worldwide. With our expertise and streamlined processes, we ensure a hassle-free journey. Whether it&#39;s for business, vacation, or study, our dedicated team provides efficient and reliable visa services tailored to your needs.','Embassy Services','Discover seamless embassy services tailored to your needs with our dedicated assistance. From visa applications to consular affairs, we streamline the process, ensuring efficiency and accuracy every step of the way.','International Driving License','Embark on your global adventures with ease by obtaining your international driving license with our comprehensive support services. We guide you through the process, ensuring all necessary paperwork is completed accurately and efficiently.','Medical Tourism','Experience seamless medical tourism with our comprehensive support services, powered by our collaboration with Bluedot Medical Assistance'),
    'ar' => array('خدماتنا','معالجة التأشيرة','نحن متخصصون في تبسيط إجراءات الحصول على تأشيرة المسافرين إلى أكثر من 15 دولة حول العالم. بفضل لدينا خبرةنا المبسطة، نضمن رحلة خالية من الشمس. سواء كان أمر العمل أو الإجازة أو الدراسة، يقدم فريقنا المتخصص خدمات تأشيرات فعالة ومصممة خصيصاً للدفع.','خدمات السفارة','اكتشف خدمات السفارة السلسة والمصممة خصيصًا لتلبية احتياجاتك من خلال مساعدتنا المخصصة. بدءًا من طلبات التأشيرة وحتى الشؤون القنصلية، نقوم بتبسيط العملية، مما يضمن الكفاءة والدقة في كل خطوة على الطريق.','رخصة القيادة الدولية','انطلق في مغامراتك العالمية بسهولة من خلال الحصول على رخصة القيادة الدولية الخاصة بك مع خدمات الدعم الشاملة التي نقدمها. نحن نرشدك خلال هذه العملية، ونضمن إكمال جميع الأوراق اللازمة بدقة وكفاءة.','سياحة طبية','استمتع بتجربة سياحة طبية سلسة من خلال خدمات الدعم الشاملة التي نقدمها، والتي تدعمها تعاوننا مع Bluedot Medical Assistance')
);

$countries = array(
    'en' => array('Explore','UK','USA','Canada','Brazil','Mexico','Australia','China','India','EU','Russia (Online)','Japan (Online)','Guinea (Online)','Thailand','View More'),
    'ar' => array('يستكشف','المملكة المتحدة','الولايات المتحدة الأمريكية','كندا','البرازيل','المكسيك','أستراليا','الصين','الهند','الاتحاد الأوروبي','روسيا (عبر الإنترنت)','اليابان (عبر الإنترنت)','غينيا (عبر الإنترنت)','تايلاند','عرض المزيد')
    
);

$medical_service = array(
    'en' => array('MEDICAL SERVICES','Welcome to Leap Visa Travel Agency Medical Assistance, your premier destination for a seamless fusion of healthcare and travel services. We pride ourselves on offering a comprehensive range of offerings designed to cater to your every need, including bespoke medical tourism packages, expert medical assistance, reliable air ambulance services, and more. Whether you&aposre seeking top-notch medical treatments abroad, require assistance navigating healthcare systems, or need swift and efficient medical transportation, we&aposve got you covered. Explore our array of services below and let us be your trusted partner in health and travel. Click the button below to discover the possibilities.','MEDICAL TOURISM','Medical tourism serves as a pivotal pathway in healthcare, facilitating access to specialized treatments and procedures across international borders. This industry enables individuals to seek medical care abroad, often for reasons such as cost savings, shorter wait times, or access to cutting-edge treatments not available in their home countries.','AIR AMBULANCE','Air ambulances play a vital role as lifelines in medical transport, delivering swift and specialized care to patients in critical need. These airborne intensive care units are outfitted with an array of advanced medical equipment and medications to administer life-saving interventions during transit.'),
    'ar' => array('الخدمات الطبية','مرحبًا بك في المساعدة الطبية لوكالة Leap Visa للسفر، وجهتك الأولى للحصول على مزيج سلس من خدمات الرعاية الصحية والسفر. نحن نفخر بتقديم مجموعة شاملة من العروض المصممة لتلبية جميع احتياجاتك، بما في ذلك باقات السياحة الطبية المخصصة والمساعدة الطبية المتخصصة وخدمات الإسعاف الجوي الموثوقة والمزيد. سواء كنت تبحث عن علاجات طبية رفيعة المستوى في الخارج، أو تحتاج إلى مساعدة في التعامل مع أنظمة الرعاية الصحية، أو تحتاج إلى نقل طبي سريع وفعال، فلدينا ما تحتاجه. استكشف مجموعة الخدمات أدناه ودعنا نكون شريكك الموثوق به في مجال الصحة والسفر. انقر على الزر أدناه لاكتشاف الاحتمالات.','سياحة طبية','تعد السياحة الطبية بمثابة مسار محوري في الرعاية الصحية، مما يسهل الوصول إلى العلاجات والإجراءات المتخصصة عبر الحدود الدولية. تمكن هذه الصناعة الأفراد من طلب الرعاية الطبية في الخارج، غالبًا لأسباب مثل توفير التكاليف، أو فترات انتظار أقصر، أو الوصول إلى العلاجات المتطورة غير المتوفرة في بلدانهم الأصلية.','الإسعاف الجوي','تلعب سيارات الإسعاف الجوي دورًا حيويًا باعتبارها شريان الحياة في النقل الطبي، حيث تقدم رعاية سريعة ومتخصصة للمرضى الذين هم في أمس الحاجة إليها. تم تجهيز وحدات العناية المركزة المحمولة جواً بمجموعة من المعدات الطبية والأدوية المتقدمة لإدارة التدخلات المنقذة للحياة أثناء النقل.')
);

$join_adventure = array(
    'en' => array('JOIN OUR ADVENTURE','Subscribe'),
    'ar' => array('انضم إلى مغامرتنا','يشترك')
);

$get_in_touch = array(
    'en' => array('GET IN TOUCH','LEAP VISA TRAVELS','Located in: Opposite to Dove Plaza',
    '4486 Umm Al Hamam St, Umm Al Hamam Al Sharqi,','حي, 6803, Riyadh 12321, Saudi Arabia','FOLLOW US ON','SEND US A MESSAGE','SUBMIT'),
    'ar' => array('ابقى على تواصل','الموقع: مقابل دوف بلازا','4486 شارع أم الحمام, أم الحمام الشرقي,','6803، الرياض 12321، المملكة العربية السعودية','اتبعنا','أرسل لنا رسالة','يُقدِّم')
);

$footer = array(
    'en' => array('Leap Visa Travel Agency','Home','About','Our Services','Explore','Medical','Contact'),
    'ar' => array('وكالة ليب فيزا للسفر','بيت','عن','خدماتنا','يستكشف','طبي','اتصال')
);

$learn_more = array(
    'en' => array('Learn More'),
    'ar' => array('يتعلم أكثر')
);

$medical_popup = array(
    'en' => array('MEDICAL TOURISM','We support patients to get affordable treatments in Countries like India, Pakistan, Bangladesh etc.','We provide treatment options in European and western countries as well, like Germany, Italy, USA, czech republic, UK etc.','Support to get invitation letter for the visa processing.','We support patient throughout the entire patient journey with 24/7 control center and providing individual attention through case manager support.','Our vast hospital network helps the patients to have different cost effective and quality options.','The treatment plan and estimates are provided before travel and help the patient with comprehensive package which include all the services including travel and accommodation as per the customer needs.','Process','Collection all the latest medical report from the patient.','Understand and identify client requirements such as his treatment destination preferences, package inclusions and any other special requests if any.','Share the reports and all valid information with Bluedot Team.','Bluedot team will share the treatment plan and estimates from the hospital’s asper the client requirements.','Share the plan with client and confirm his choice.','Visa invitation letter from hospital through Bluedot team.','Visa Processing by Leap Team.','Virtual consultation, if required.','Case manager allocation by Bluedot Team.','Timely updation on the treatment progress to Leap by Bluedot team.','Patient feedback.'),
    'ar' => array('سياحة طبية','نحن ندعم المرضى للحصول على علاجات ميسورة التكلفة في دول مثل الهند وباكستان وبنغلاديش وغيرها.','نحن نقدم خيارات العلاج في الدول الأوروبية والغربية أيضًا، مثل ألمانيا وإيطاليا والولايات المتحدة الأمريكية وجمهورية التشيك والمملكة المتحدة وغيرها.','الدعم للحصول على خطاب دعوة لمعالجة التأشيرة.','دعم للحصول على خطاب دعوة لمعالجة التأشيرة.','نحن ندعم المريض طوال رحلة المريض بأكملها من خلال مركز تحكم يعمل على مدار الساعة طوال أيام الأسبوع ونوفر الاهتمام الفردي من خلال دعم مدير الحالة.','تساعد شبكة المستشفيات الواسعة لدينا المرضى في الحصول على خيارات مختلفة فعالة من حيث التكلفة والجودة.','يتم توفير خطة العلاج والتقديرات قبل السفر ومساعدة المريض بحزمة شاملة تشمل جميع الخدمات بما في ذلك السفر والإقامة حسب احتياجات العميل.','عملية','جمع كافة التقارير الطبية الأخيرة من المريض.','فهم وتحديد متطلبات العميل مثل تفضيلات وجهة العلاج الخاصة به، ومزايا الحزمة وأي طلبات خاصة أخرى إن وجدت.','شارك التقارير وجميع المعلومات الصحيحة مع فريق Bluedot.','سيقوم فريق Bluedot بمشاركة خطة العلاج والتقديرات من المستشفى وفقًا لمتطلبات العميل.','شارك الخطة مع العميل وأكد اختياره.','خطاب دعوة للحصول على التأشيرة من المستشفى من خلال فريق Bluedot.','معالجة التأشيرة بواسطة فريق Leap.','التشاور الافتراضي، إذا لزم الأمر.','تخصيص مدير الحالة بواسطة فريق Bluedot.','التحديث في الوقت المناسب بشأن تقدم العلاج المقدم من فريق Leap بواسطة Bluedot.','ردود فعل المريض.')
);

$air_ambulance = array(
    'en' => array('AIR AMBULANCE','We support patients to get affordable treatments in Countries like India, Pakistan, Bangladesh etc.','We provide treatment options in European and western countries as well, like Germany, Italy, USA, czech republic, UK etc.','Support to get invitation letter for the visa processing.','We support patient throughout the entire patient journey with 24/7 control center and providing individual attention through case manager support.','Our vast hospital network helps the patients to have different cost effective and quality options.','The treatment plan and estimates are provided before travel and help the patient with comprehensive package which include all the services including travel and accommodation as per the customer needs.','Process','Collection all the latest medical report from the patient.','Understand and identify client requirements such as his treatment destination preferences, package inclusions and any other special requests if any.','Share the reports and all valid information with Bluedot Team.','Bluedot team will share the treatment plan and estimates from the hospital’s asper the client requirements.','Share the plan with client and confirm his choice.','Visa invitation letter from hospital through Bluedot team.','Visa Processing by Leap Team.','Virtual consultation, if required.','Case manager allocation by Bluedot Team.','Timely updation on the treatment progress to Leap by Bluedot team.','Patient feedback.'),
    'ar' => array('الإسعاف الجوي','نحن ندعم المرضى للحصول على علاجات ميسورة التكلفة في دول مثل الهند وباكستان وبنغلاديش وغيرها.','نحن نقدم خيارات العلاج في الدول الأوروبية والغربية أيضًا، مثل ألمانيا وإيطاليا والولايات المتحدة الأمريكية وجمهورية التشيك والمملكة المتحدة وغيرها.','دعم للحصول على خطاب دعوة لمعالجة التأشيرة.','نحن ندعم المريض طوال رحلة المريض بأكملها من خلال مركز تحكم يعمل على مدار الساعة طوال أيام الأسبوع ونوفر الاهتمام الفردي من خلال دعم مدير الحالة.','تساعد شبكة المستشفيات الواسعة لدينا المرضى في الحصول على خيارات مختلفة فعالة من حيث التكلفة والجودة.','يتم توفير خطة العلاج والتقديرات قبل السفر ومساعدة المريض بحزمة شاملة تشمل جميع الخدمات بما في ذلك السفر والإقامة حسب احتياجات العميل.','عملية','جمع كافة التقارير الطبية الأخيرة من المريض.','فهم وتحديد متطلبات العميل مثل تفضيلات وجهة العلاج الخاصة به، ومزايا الحزمة وأي طلبات خاصة أخرى إن وجدت.','شارك التقارير وجميع المعلومات الصحيحة مع فريق Bluedot.','سيقوم فريق Bluedot بمشاركة خطة العلاج والتقديرات من المستشفى وفقًا لمتطلبات العميل.','شارك الخطة مع العميل وأكد اختياره.','خطاب دعوة للتأشيرة من المستشفى من خلال فريق Bluedot.','معالجة التأشيرة من قبل فريق Leap.','الاستشارة الافتراضية، إذا لزم الأمر.','تخصيص مدير الحالة بواسطة فريق Bluedot.','التحديث في الوقت المناسب بشأن تقدم العلاج المقدم من فريق Leap بواسطة Bluedot.','ردود فعل المريض.')
)

?>